version: "3.9"

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: mentor_mentee
      FLASK_ENV: production
    depends_on:
      - mongo

  frontend:
    build: ./front2
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: